// <auto-generated />
using Calia.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calia.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241002220206_addProducts")]
    partial class addProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calia.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AvailableProducts")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Espresso",
                            Price = 70.0
                        },
                        new
                        {
                            ProductId = 2,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Double Espresso",
                            Price = 90.0
                        },
                        new
                        {
                            ProductId = 3,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Espresso Macchiato",
                            Price = 75.0
                        },
                        new
                        {
                            ProductId = 4,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Americano",
                            Price = 95.0
                        },
                        new
                        {
                            ProductId = 5,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Latte",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 6,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Flat White",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 7,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Cappuccino",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 8,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Cortado",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 9,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Caramel Macchiato",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 10,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Mocha",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 11,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "White Mocha",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 12,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Zebra Mocha",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 13,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Lotus Latte",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 14,
                            AvailableProducts = 0,
                            CategoryId = 1,
                            Name = "Pumpkin Spice Latte",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 15,
                            AvailableProducts = 0,
                            CategoryId = 2,
                            Name = "V60",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 16,
                            AvailableProducts = 0,
                            CategoryId = 2,
                            Name = "Chemex",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 17,
                            AvailableProducts = 0,
                            CategoryId = 2,
                            Name = "Filtre Kahve",
                            Price = 90.0
                        },
                        new
                        {
                            ProductId = 18,
                            AvailableProducts = 0,
                            CategoryId = 2,
                            Name = "Black Eye",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 19,
                            AvailableProducts = 0,
                            CategoryId = 2,
                            Name = "Red Eye",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 20,
                            AvailableProducts = 0,
                            CategoryId = 2,
                            Name = "Death Eye",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 21,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Çay",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 22,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Fincan Çay",
                            Price = 45.0
                        },
                        new
                        {
                            ProductId = 23,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Sütlü Çay",
                            Price = 65.0
                        },
                        new
                        {
                            ProductId = 24,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Türk Kahvesi",
                            Price = 70.0
                        },
                        new
                        {
                            ProductId = 25,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Double Türk Kahvesi",
                            Price = 90.0
                        },
                        new
                        {
                            ProductId = 26,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Sütlü Menengiç",
                            Price = 75.0
                        },
                        new
                        {
                            ProductId = 27,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Menengiç Kahvesi",
                            Price = 75.0
                        },
                        new
                        {
                            ProductId = 28,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Sıcak Çikolata",
                            Price = 85.0
                        },
                        new
                        {
                            ProductId = 29,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Beyaz Çikolata",
                            Price = 85.0
                        },
                        new
                        {
                            ProductId = 30,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Salep",
                            Price = 85.0
                        },
                        new
                        {
                            ProductId = 31,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Chai Tea Latte",
                            Price = 105.0
                        },
                        new
                        {
                            ProductId = 32,
                            AvailableProducts = 0,
                            CategoryId = 3,
                            Name = "Ballı Süt",
                            Price = 70.0
                        },
                        new
                        {
                            ProductId = 33,
                            AvailableProducts = 0,
                            CategoryId = 4,
                            Name = "Su",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 34,
                            AvailableProducts = 0,
                            CategoryId = 4,
                            Name = "Soda",
                            Price = 50.0
                        },
                        new
                        {
                            ProductId = 35,
                            AvailableProducts = 0,
                            CategoryId = 4,
                            Name = "Meyveli Soda",
                            Price = 55.0
                        },
                        new
                        {
                            ProductId = 36,
                            AvailableProducts = 0,
                            CategoryId = 4,
                            Name = "Churchill",
                            Price = 60.0
                        },
                        new
                        {
                            ProductId = 37,
                            AvailableProducts = 0,
                            CategoryId = 4,
                            Name = "Vişne Soda",
                            Price = 70.0
                        },
                        new
                        {
                            ProductId = 38,
                            AvailableProducts = 0,
                            CategoryId = 4,
                            Name = "Red Bull",
                            Price = 90.0
                        },
                        new
                        {
                            ProductId = 39,
                            AvailableProducts = 0,
                            CategoryId = 4,
                            Name = "Detox",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 40,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Americano",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 41,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Filtre Kahve",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 42,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Latte",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 43,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Mocha",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 44,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice White Mocha",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 45,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Zebra Mocha",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 46,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Red Eye",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 47,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Black Eye",
                            Price = 105.0
                        },
                        new
                        {
                            ProductId = 48,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Lotus Latte",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 49,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Ice Cold Brew Latte",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 50,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Frappe",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 51,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Affagato",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 52,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Freddo Cappuccino",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 53,
                            AvailableProducts = 0,
                            CategoryId = 5,
                            Name = "Cold Brew",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 54,
                            AvailableProducts = 0,
                            CategoryId = 6,
                            Name = "Ihlamur",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 55,
                            AvailableProducts = 0,
                            CategoryId = 6,
                            Name = "Yeşil Çay",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 56,
                            AvailableProducts = 0,
                            CategoryId = 6,
                            Name = "Yaseminli Yeşil Çay",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 57,
                            AvailableProducts = 0,
                            CategoryId = 6,
                            Name = "Kış Çayı",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 58,
                            AvailableProducts = 0,
                            CategoryId = 6,
                            Name = "Ada Çayı",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 59,
                            AvailableProducts = 0,
                            CategoryId = 6,
                            Name = "Hibiscus",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 60,
                            AvailableProducts = 0,
                            CategoryId = 7,
                            Name = "Çilek",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 61,
                            AvailableProducts = 0,
                            CategoryId = 7,
                            Name = "Blueberry",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 62,
                            AvailableProducts = 0,
                            CategoryId = 7,
                            Name = "Mango",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 65,
                            AvailableProducts = 0,
                            CategoryId = 10,
                            Name = "Limonata",
                            Price = 90.0
                        },
                        new
                        {
                            ProductId = 66,
                            AvailableProducts = 0,
                            CategoryId = 10,
                            Name = "Çilekli Limonata",
                            Price = 95.0
                        },
                        new
                        {
                            ProductId = 67,
                            AvailableProducts = 0,
                            CategoryId = 10,
                            Name = "Naneli Limonata",
                            Price = 95.0
                        },
                        new
                        {
                            ProductId = 68,
                            AvailableProducts = 0,
                            CategoryId = 10,
                            Name = "Berry Hibiscus",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 69,
                            AvailableProducts = 0,
                            CategoryId = 10,
                            Name = "Hibiscus Ice Tea",
                            Price = 90.0
                        },
                        new
                        {
                            ProductId = 70,
                            AvailableProducts = 0,
                            CategoryId = 10,
                            Name = "Cool Lime",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 71,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Bluebaby",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 72,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Hermosa",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 73,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Sweet Dreams",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 74,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Summersun",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 75,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Mojito",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 76,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Çilekli Mojito",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 77,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Blueberry Jalep",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 78,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Winterfazz",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 79,
                            AvailableProducts = 0,
                            CategoryId = 11,
                            Name = "Sunlight",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 80,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Çikolata",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 81,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Karamel",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 82,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Vanilya",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 83,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Fındık",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 84,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Badem",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 85,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Irish",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 86,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Hindistan Cevizi",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 87,
                            AvailableProducts = 0,
                            CategoryId = 12,
                            Name = "Toffee Nut",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 90,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Pavlova",
                            Price = 180.0
                        },
                        new
                        {
                            ProductId = 91,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Brownie",
                            Price = 170.0
                        },
                        new
                        {
                            ProductId = 92,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "San Sebastian",
                            Price = 180.0
                        },
                        new
                        {
                            ProductId = 93,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Paris-Brest",
                            Price = 180.0
                        },
                        new
                        {
                            ProductId = 94,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Makaron",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 95,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Magnolia",
                            Price = 160.0
                        },
                        new
                        {
                            ProductId = 96,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Lotus Magnolia",
                            Price = 160.0
                        },
                        new
                        {
                            ProductId = 97,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Afife",
                            Price = 170.0
                        },
                        new
                        {
                            ProductId = 98,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Kedi Dili Tiramisu",
                            Price = 170.0
                        },
                        new
                        {
                            ProductId = 99,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Floransa Cake",
                            Price = 160.0
                        },
                        new
                        {
                            ProductId = 100,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Orman Meyveli Cheesecake",
                            Price = 155.0
                        },
                        new
                        {
                            ProductId = 101,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Callia Kruvasan",
                            Price = 190.0
                        },
                        new
                        {
                            ProductId = 102,
                            AvailableProducts = 0,
                            CategoryId = 13,
                            Name = "Callia",
                            Price = 200.0
                        },
                        new
                        {
                            ProductId = 103,
                            AvailableProducts = 0,
                            CategoryId = 14,
                            Name = "Kruvasan Sandwich",
                            Price = 180.0
                        },
                        new
                        {
                            ProductId = 104,
                            AvailableProducts = 0,
                            CategoryId = 14,
                            Name = "Callia Kruvasan",
                            Price = 190.0
                        },
                        new
                        {
                            ProductId = 105,
                            AvailableProducts = 0,
                            CategoryId = 9,
                            Name = "Çilek",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 106,
                            AvailableProducts = 0,
                            CategoryId = 9,
                            Name = "Muz",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 107,
                            AvailableProducts = 0,
                            CategoryId = 9,
                            Name = "Blueberry",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 108,
                            AvailableProducts = 0,
                            CategoryId = 9,
                            Name = "Mango Ananas",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 109,
                            AvailableProducts = 0,
                            CategoryId = 9,
                            Name = "Mango",
                            Price = 100.0
                        });
                });

            modelBuilder.Entity("Calia.Services.ProductAPI.Models.ProductExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtraName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductExtras");
                });

            modelBuilder.Entity("Calia.Services.ProductAPI.Models.ProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMaterials");
                });

            modelBuilder.Entity("Calia.Services.ProductAPI.Models.ProductExtra", b =>
                {
                    b.HasOne("Calia.Services.ProductAPI.Models.Product", null)
                        .WithMany("ProductExtras")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calia.Services.ProductAPI.Models.ProductMaterial", b =>
                {
                    b.HasOne("Calia.Services.ProductAPI.Models.Product", null)
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calia.Services.ProductAPI.Models.Product", b =>
                {
                    b.Navigation("ProductExtras");

                    b.Navigation("ProductMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
