// <auto-generated />
using System;
using Calia.Services.OrderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calia.Services.OrderAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240911232626_addtableno")]
    partial class addtableno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderDetailsId");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.OrderExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtraName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderDetailsId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailsId");

                    b.ToTable("OrderExtras");
                });

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.OrderHeader", b =>
                {
                    b.Property<int>("OrderHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderHeaderId"));

                    b.Property<string>("MasaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderHeaderId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.TableNo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MasaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TableNos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MasaNo = "1"
                        },
                        new
                        {
                            Id = 2,
                            MasaNo = "2"
                        },
                        new
                        {
                            Id = 3,
                            MasaNo = "3"
                        },
                        new
                        {
                            Id = 4,
                            MasaNo = "4"
                        },
                        new
                        {
                            Id = 5,
                            MasaNo = "5"
                        },
                        new
                        {
                            Id = 6,
                            MasaNo = "6"
                        },
                        new
                        {
                            Id = 7,
                            MasaNo = "7"
                        },
                        new
                        {
                            Id = 8,
                            MasaNo = "8"
                        },
                        new
                        {
                            Id = 9,
                            MasaNo = "9"
                        },
                        new
                        {
                            Id = 10,
                            MasaNo = "10"
                        },
                        new
                        {
                            Id = 11,
                            MasaNo = "11"
                        },
                        new
                        {
                            Id = 12,
                            MasaNo = "12"
                        },
                        new
                        {
                            Id = 13,
                            MasaNo = "13"
                        },
                        new
                        {
                            Id = 14,
                            MasaNo = "14"
                        },
                        new
                        {
                            Id = 15,
                            MasaNo = "15"
                        },
                        new
                        {
                            Id = 16,
                            MasaNo = "16"
                        },
                        new
                        {
                            Id = 17,
                            MasaNo = "17"
                        },
                        new
                        {
                            Id = 18,
                            MasaNo = "18"
                        },
                        new
                        {
                            Id = 19,
                            MasaNo = "19"
                        },
                        new
                        {
                            Id = 20,
                            MasaNo = "20"
                        },
                        new
                        {
                            Id = 21,
                            MasaNo = "21"
                        },
                        new
                        {
                            Id = 22,
                            MasaNo = "22"
                        },
                        new
                        {
                            Id = 23,
                            MasaNo = "23"
                        },
                        new
                        {
                            Id = 24,
                            MasaNo = "24"
                        },
                        new
                        {
                            Id = 25,
                            MasaNo = "25"
                        },
                        new
                        {
                            Id = 26,
                            MasaNo = "26"
                        },
                        new
                        {
                            Id = 27,
                            MasaNo = "27"
                        },
                        new
                        {
                            Id = 28,
                            MasaNo = "28"
                        },
                        new
                        {
                            Id = 29,
                            MasaNo = "29"
                        },
                        new
                        {
                            Id = 30,
                            MasaNo = "30"
                        },
                        new
                        {
                            Id = 31,
                            MasaNo = "31"
                        });
                });

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.OrderDetails", b =>
                {
                    b.HasOne("Calia.Services.OrderAPI.Models.OrderHeader", "OrderHeader")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");
                });

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.OrderExtra", b =>
                {
                    b.HasOne("Calia.Services.OrderAPI.Models.OrderDetails", null)
                        .WithMany("ProductExtrasList")
                        .HasForeignKey("OrderDetailsId");
                });

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.OrderDetails", b =>
                {
                    b.Navigation("ProductExtrasList");
                });

            modelBuilder.Entity("Calia.Services.OrderAPI.Models.OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
